# Site settings
title: Taka Goto
description: Full Stack Dev | Esports Fanatic | Dog Lover
baseurl: ""
url: "https://takagoto.github.io"
github_username: TakaGoto

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

permalink: /blog/:title/
excerpt_separator: "\n\n"

# Only show these pages in the header navigation
header_pages:
  - about.md
