# Site settings
title: Taka Goto
description: Building in public. Shipping iOS apps.
baseurl: ""
url: "https://takagoto.github.io"
github_username: TakaGoto

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /blog/:title/
excerpt_separator: "\n\n"

# Navigation
header_pages:
  - lab.html
  - about.md
